// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uypmzhnwccwqtbytbsgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5cG16aG53Y2N3cXRieXRic2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Njk0MjQsImV4cCI6MjA1OTQ0NTQyNH0.gnopO4ZkqTbWe9_WFWsLUDK1F7ZXz5i5KHCUVawws6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);